/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HBtn: typeof import('./src/components/HBtn.vue')['default']
    HChip: typeof import('./src/components/HChip.vue')['default']
    HSpinner: typeof import('./src/components/HSpinner.vue')['default']
    HSwitch: typeof import('./src/components/HSwitch.vue')['default']
    HTextInput: typeof import('./src/components/HTextInput.vue')['default']
    IconoirCheck: typeof import('~icons/iconoir/check')['default']
    IconoirTrash: typeof import('~icons/iconoir/trash')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
