/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HBtn: typeof import('./src/components/HBtn.vue')['default']
    HChip: typeof import('./src/components/HChip.vue')['default']
    HChipGroup: typeof import('./src/components/HChipGroup.vue')['default']
    HDialog: typeof import('./src/components/HDialog.vue')['default']
    HDrawer: typeof import('./src/components/HDrawer.vue')['default']
    HIconRating: typeof import('~icons/h-icon/rating')['default']
    HIconStarRating: typeof import('~icons/h-icon/star-rating')['default']
    HIconSTarRating: typeof import('~icons/h-icon/s-tar-rating')['default']
    HMenu: typeof import('./src/components/HMenu.vue')['default']
    HRadio: typeof import('./src/components/HRadio.vue')['default']
    HRadioGroup: typeof import('./src/components/HRadioGroup.vue')['default']
    HRating: typeof import('./src/components/HRating.vue')['default']
    HSpinner: typeof import('./src/components/HSpinner.vue')['default']
    HSwitch: typeof import('./src/components/HSwitch.vue')['default']
    HTable: typeof import('./src/components/HTable.vue')['default']
    HTextInput: typeof import('./src/components/HTextInput.vue')['default']
    IconoirArrowRight: typeof import('~icons/iconoir/arrow-right')['default']
    IconoirCheck: typeof import('~icons/iconoir/check')['default']
    IconoirCheckCircleSolid: typeof import('~icons/iconoir/check-circle-solid')['default']
    IconoirCircle: typeof import('~icons/iconoir/circle')['default']
    IconoirTrash: typeof import('~icons/iconoir/trash')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
