/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/btn': RouteRecordInfo<'/btn', '/btn', Record<never, never>, Record<never, never>>,
    '/chips': RouteRecordInfo<'/chips', '/chips', Record<never, never>, Record<never, never>>,
    '/dialog': RouteRecordInfo<'/dialog', '/dialog', Record<never, never>, Record<never, never>>,
    '/inputs': RouteRecordInfo<'/inputs', '/inputs', Record<never, never>, Record<never, never>>,
    '/menu': RouteRecordInfo<'/menu', '/menu', Record<never, never>, Record<never, never>>,
    '/spinner': RouteRecordInfo<'/spinner', '/spinner', Record<never, never>, Record<never, never>>,
    '/switch': RouteRecordInfo<'/switch', '/switch', Record<never, never>, Record<never, never>>,
  }
}
